import type { Locale } from "./types";

export const en = {
  brand: "Ethio Wellness",
  "nav.home": "Home",
  "nav.services": "Services",
  "nav.professionals": "Professionals",
  "nav.signIn": "Sign in",
  "nav.createAccount": "Create account",
  "nav.mySessions": "My sessions",
  "nav.sessions": "Sessions",
  "nav.account": "Account",
  "nav.bookings": "Bookings",
  "nav.availability": "Availability",
  "nav.profile": "Profile",
  "footer.about":
    "Ethio Wellness connects you with licensed Ethiopian counselors and wellness professionals, in the language you think in.",
  "footer.explore": "Explore",
  "footer.support": "Support",
  "footer.legal": "Legal",
  "footer.help": "Help center",
  "footer.contact": "Contact",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.base": "© 2026 Ethio Wellness · Made with care in Addis Ababa",
  "splash.tagline": "Support for your mind, in the language of your heart.",
  "home.kicker": "Counseling in your language",
  "home.h1": "Support for your mind, in the language of your heart.",
  "home.sub":
    "Ethio Wellness connects you with Ethiopian counselors and wellness professionals — in Amharic, Tigrinya, Afaan Oromoo, and English. Browse freely, book when you're ready.",
  "home.ctaProfessionals": "Browse professionals",
  "home.ctaServices": "Explore services",
  "home.trust1": "Licensed Ethiopian professionals",
  "home.trust2": "Sessions in 4+ languages",
  "home.trust3": "Private & secure",
  "home.howTitle": "How it works",
  "home.how1Title": "Find your counselor",
  "home.how1Body": "Browse by specialty, language, and availability.",
  "home.how2Title": "Book a 1-hour session",
  "home.how2Body": "Pick a time that works for you.",
  "home.how3Title": "Meet by video",
  "home.how3Body": "Join from your phone or computer.",
  "home.popular": "Popular services",
  "home.seeAll": "See all categories →",
  "home.featured": "Featured professionals",
  "home.browseAll": "Browse all professionals →",
  "login.title": "Welcome back",
  "login.sub": "Sign in to manage your sessions and bookings.",
  "login.email": "Email",
  "login.password": "Password",
  "login.submit": "Sign in",
  "login.forgot": "Forgot your password?",
  "login.newHere": "New here? Create a free account",
  "register.title": "Create your free account",
  "register.sub": "Book sessions, manage your bookings, and join by video — all in one place.",
  "register.name": "Full name",
  "register.submit": "Create account",
  "register.terms": "By creating an account you agree to the Terms and Privacy policy.",
  "register.hasAccount": "Already have an account? Sign in",
  "role.title": "How will you use Ethio Wellness?",
  "role.clientTitle": "I'm looking for support",
  "role.clientBody": "Browse counselors and book sessions.",
  "role.proTitle": "I'm a professional",
  "role.proBody": "Offer sessions and manage your practice.",
  "forgot.title": "Reset your password",
  "forgot.sub": "Enter your email and we'll send you a reset link.",
  "forgot.submit": "Send reset link",
  "forgot.back": "Back to sign in",
  "reset.title": "Choose a new password",
  "reset.sub": "Make it something you'll remember.",
  "reset.password": "New password",
  "reset.confirm": "Confirm new password",
  "reset.submit": "Save new password",
  "expired.title": "Your session expired",
  "expired.body": "Please sign in again to continue.",
  "gate.title": "Sign in to book this session",
  "gate.body":
    "You can keep browsing as a guest — but booking needs a free account. We'll bring you right back to this slot after you sign in.",
  "gate.signIn": "Sign in",
  "gate.create": "Create free account",
  "gate.continue": "Continue browsing",
  "services.title": "Services",
  "services.sub": "Find the kind of support you're looking for.",
  "services.search": "Search categories…",
  "services.available": "professionals available",
  "pros.title": "Professionals",
  "pros.sub": "Browse counselors by specialty, language, and availability.",
  "pros.search": "Search by name…",
  "pros.clear": "Clear filters",
  "pros.viewProfile": "View profile",
  "pros.next": "Next",
  "pros.emptyTitle": "No matches found",
  "pros.emptyBody": "Try a different name, specialty, or language.",
  "detail.about": "About",
  "detail.specialties": "Specialties",
  "detail.languages": "Languages",
  "detail.availability": "Availability this week",
  "detail.hourNote": "All sessions are 1 hour.",
  "detail.reviews": "What clients say",
  "detail.book": "Book",
  "detail.emptyTitle": "No open slots right now",
  "detail.emptyBody":
    "This counselor hasn't added new times yet. Check back soon or browse similar professionals.",
  "detail.browseSimilar": "Browse similar",
  "onboard.title": "A few quick questions",
  "onboard.sub": "This helps us recommend the right professionals for you.",
  "onboard.looking": "What are you looking for?",
  "onboard.continue": "Continue",
  "onboard.skip": "Skip for now",
  "prefs.title": "What are you looking for?",
  "prefs.sub":
    "Choose the languages you're comfortable with and the kinds of support you want. We'll use these to recommend counselors — you can change them anytime in Account.",
  "prefs.languages": "Preferred language(s)",
  "prefs.carried": "Carried over from step 1 — adjust here if you like.",
  "prefs.pickLang": "Pick every language you're comfortable talking in. At least one is required.",
  "prefs.support": "Types of support",
  "prefs.supportHint": "Check at least one kind of support you're interested in.",
  "prefs.search": "Search types of support…",
  "prefs.growing": "New types of support are added as more counselors join — this list keeps growing.",
  "prefs.back": "Back",
  "prefs.skip": "Skip",
  "prefs.saved": "Your preferences are saved.",
  "clientHome.hello": "Hello, Miki",
  "clientHome.next": "Next session",
  "clientHome.recommended": "Recommended for you",
  "clientHome.continue": "Continue browsing",
  "book.title": "Book your session",
  "book.step1": "1. Pick a date",
  "book.step2": "2. Choose a 1-hour slot",
  "book.continue": "Continue to payment",
  "book.cancelNote": "Free cancellation up to 24 hours before.",
  "book.duration": "1 hour",
  "pay.title": "Complete your booking",
  "pay.line": "1-hour session with",
  "pay.card": "Card number",
  "pay.expiry": "Expiry",
  "pay.cvc": "CVC",
  "pay.name": "Name on card",
  "pay.demo": "Demo checkout — no real payment is processed.",
  "confirm.title": "You're booked!",
  "confirm.sub": "We sent the details to your email.",
  "confirm.view": "View my sessions",
  "confirm.home": "Back home",
  "confirm.browse": "Keep browsing",
  "sessions.title": "My sessions",
  "sessions.upcoming": "Upcoming",
  "sessions.past": "Past",
  "sessions.cancelled": "Cancelled",
  "sessions.emptyTitle": "No sessions yet",
  "sessions.emptyBody": "When you book a session it will appear here.",
  "sessions.join": "Join session",
  "sessions.details": "View details",
  "session.professional": "Professional",
  "session.datetime": "Date & time",
  "session.specialty": "Specialty",
  "session.duration": "Duration",
  "session.language": "Language",
  "session.status": "Status",
  "session.reschedule": "Reschedule",
  "session.cancel": "Cancel session",
  "session.joinNote": "You'll be able to join 15 minutes before your session starts.",
  "proOnboard.title": "Tell us about your practice",
  "proOnboard.sub": "Clients will see this on your public profile.",
  "proOnboard.titleField": "Professional title",
  "proOnboard.city": "City",
  "proOnboard.credentials": "Credentials",
  "proOnboard.bio": "A few sentences about how you work.",
  "proHome.hello": "Hello, Hana",
  "proHome.complete": "Complete your profile",
  "proHome.upcoming": "Upcoming bookings",
  "proHome.availability": "Manage availability",
  "proHome.bookings": "View bookings",
  "proHome.edit": "Edit profile",
  "proProfile.title": "Your public profile",
  "proProfile.note": "This is what clients see when they visit your page.",
  "proProfile.edit": "Edit profile",
  "proProfile.specialties": "Manage specialties",
  "proProfile.availability": "Set availability",
  "proSpecs.title": "Your specialties",
  "proSpecs.sub": "Pick the areas you work in. Clients use these to find you.",
  "proSpecs.save": "Save changes",
  "proAvail.title": "Your availability",
  "proAvail.sub": "Pick a date, then tap 1-hour slots to open them for booking.",
  "proAvail.available": "Available",
  "proAvail.booked": "Booked",
  "proAvail.note": "Booked slots can't be removed — contact support to change a confirmed session.",
  "proBookings.title": "Bookings",
  "account.title": "Account settings",
  "account.language": "Preferred language",
  "account.email": "Email",
  "account.changePassword": "Change password",
  "account.signOut": "Sign out",
  "notFound.title": "Page not found",
  "notFound.body": "The page you're looking for doesn't exist or was moved.",
  "notFound.cta": "Go home",
  "error.title": "Something went wrong",
  "error.body": "Please try again in a moment.",
  "error.cta": "Try again",
} as const;

export type CopyKey = keyof typeof en;

export const am: Partial<Record<CopyKey, string>> = {
  "nav.home": "መነሻ",
  "nav.services": "አገልግሎቶች",
  "nav.professionals": "ባለሙያዎች",
  "nav.mySessions": "የእኔ ቀጠሮዎች",
  "nav.sessions": "የእኔ ቀጠሮዎች",
  "nav.signIn": "ይግቡ",
  "nav.createAccount": "መለያ ይፍጠሩ",
  "account.signOut": "ይውጡ",
  "home.ctaProfessionals": "ባለሙያዎችን ይፈልጉ",
  "home.ctaServices": "አገልግሎቶችን ይመልከቱ",
  "detail.book": "ይያዙ",
  "home.h1": "በቋንቋዎ የሚሰጥ የስነ-ልቦና ድጋፍ።",
  "gate.title": "ይህን ቀጠሮ ለመያዝ ይግቡ",
  "gate.body": "እንደ እንግዳ መፈለግዎን መቀጠል ይችላሉ — ግን ቀጠሮ ለመያዝ ነፃ መለያ ያስፈልጋል። ከገቡ በኋላ ወደዚህ ጊዜ እንመልስዎታለን።",
  "prefs.title": "ምን እየፈለጉ ነው؟",
  "prefs.sub": "የሚመችዎ ቋንቋ እና የሚፈልጉትን የድጋፍ ዓይነት ይምረጡ። እነዚህ ምርጫዎች ተስማሚ አማካሪዎችን እንድንመክር ይረዱናል፤ በማንኛውም ጊዜ መቀየር ይችላሉ።",
  "prefs.languages": "የሚመችዎ ቋንቋ(ዎች)",
  "prefs.support": "የድጋፍ ዓይነቶች",
  "prefs.back": "ተመለስ",
  "prefs.skip": "ዝለል",
  "onboard.continue": "ቀጥል",
  "prefs.saved": "ምርጫዎችዎ ተቀምጠዋል።",
};

export function t(locale: Locale, key: CopyKey): string {
  if (locale === "am" && am[key]) {
    return am[key] as string;
  }
  return en[key];
}
