import type { Locale } from "./types";

export const en = {
  brand: "Ayzon",
  "nav.home": "Home",
  "nav.services": "Services",
  "nav.professionals": "Professionals",
  "nav.signIn": "Sign in",
  "nav.createAccount": "Create account",
  "nav.mySessions": "My sessions",
  "nav.sessions": "Sessions",
  "nav.account": "Account",
  "nav.bookings": "Bookings",
  "nav.availability": "Availability",
  "nav.profile": "Profile",
  "nav.specialties": "Specialties",
  "nav.slots": "Slots",
  "chrome.mode": "Mode",
  "chrome.bright": "Bright",
  "chrome.night": "Night",
  "footer.about":
    "Ayzon connects you with licensed Ethiopian counselors and wellness professionals, in the language you think in.",
  "footer.explore": "Explore",
  "footer.support": "Support",
  "footer.legal": "Legal",
  "footer.help": "Help center",
  "footer.contact": "Contact",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.base": "© 2026 Ayzon · ayzoncare.com · Made with care in Addis Ababa",
  "splash.tagline": "Support for your mind, in the language of your heart.",
  "home.kicker": "Now booking · No account needed",
  "home.h1": "Counseling that speaks your language.",
  "home.amharicSub": "የምክር አገልግሎት በራስዎ ቋንቋ",
  "home.sub":
    "Ayzon connects Habesha communities abroad with counseling professionals in Ethiopia who understand the language, the culture, and life between two homes.",
  "home.guestPromise": "No signup. No password. Your business stays your business.",
  "home.ctaBrowse": "Browse counselors",
  "home.ctaSignIn": "Sign in",
  "home.howTitle": "How it works",
  "home.how1Title": "Find your counselor",
  "home.how1Body":
    "Browse by language and need. Every profile shows specialties, languages, and real availability.",
  "home.how2Title": "Book as a guest",
  "home.how2Body":
    "Pick a time and check out in about 90 seconds. No account, no password — your confirmation arrives by email.",
  "home.how3Title": "Meet by video",
  "home.how3Body": "Join from your personal link at session time. Nothing to install.",
  "home.langTitle": "Counseling in your language.",
  "home.langMore": "More coming",
  "home.closeTitle": "Ready when you are.",
  "home.closeBody": "Your first session is a few taps away.",
  "login.title": "Welcome back",
  "login.sub": "Sign in to manage your sessions and bookings.",
  "login.privacy": "Your details stay private — always.",
  "login.invalid": "Incorrect email or password. Try again or reset your password.",
  "login.email": "Email",
  "login.password": "Password",
  "login.submit": "Sign in",
  "login.forgot": "Forgot your password?",
  "login.newHere": "New here? Create a free account",
  "register.title": "Create your free account",
  "register.sub": "Book sessions, manage your bookings, and join by video — all in one place.",
  "register.name": "Full name",
  "register.submit": "Create account",
  "register.terms": "By creating an account you agree to the Terms and Privacy policy.",
  "register.hasAccount": "Already have an account? Sign in",
  "role.title": "How will you use Ayzon?",
  "role.clientTitle": "I'm looking for support",
  "role.clientBody": "Browse counselors and book sessions.",
  "role.proTitle": "I'm a professional",
  "role.proBody": "Offer sessions and manage your practice.",
  "forgot.title": "Reset your password",
  "forgot.sub": "Enter your email and we'll send you a reset link.",
  "forgot.submit": "Send reset link",
  "forgot.back": "Back to sign in",
  "reset.title": "Choose a new password",
  "reset.sub": "Make it something you'll remember.",
  "reset.password": "New password",
  "reset.confirm": "Confirm new password",
  "reset.submit": "Save new password",
  "expired.title": "Your session expired",
  "expired.body": "Please sign in again to continue.",
  "gate.title": "Sign in to book this session",
  "gate.body":
    "You can keep browsing as a guest — but booking needs a free account. We'll bring you right back to this slot after you sign in.",
  "gate.signIn": "Sign in",
  "gate.create": "Create free account",
  "gate.continue": "Continue browsing",
  "services.title": "What kind of support are you looking for?",
  "services.sub": "Find the kind of support you're looking for.",
  "services.search": "Search categories…",
  "services.available": "professionals available",
  "services.more": "More services are on the way",
  "services.request": "Request a service",
  "pros.title": "Find your counselor",
  "pros.sub": "Browse freely — no account needed. Booking is the only step that asks you to sign in.",
  "pros.search": "Search by name…",
  "pros.searchLabel": "Search by name",
  "pros.language": "Language",
  "pros.specialty": "Specialty",
  "pros.availability": "Availability",
  "pros.sort": "Sort by",
  "pros.anyTime": "Any time",
  "pros.today": "Today",
  "pros.thisWeek": "This week",
  "pros.soonest": "Soonest available",
  "pros.highest": "Highest rated",
  "pros.showing": "Showing",
  "pros.count": "professionals",
  "pros.clear": "Clear all filters",
  "pros.filters": "Filters",
  "pros.showResults": "Show results",
  "pros.nextOpen": "Next open",
  "pros.all": "All",
  "pros.viewProfile": "View profile",
  "pros.next": "Next",
  "pros.emptyTitle": "No matches found",
  "pros.emptyBody": "Try a different name, specialty, or language.",
  "detail.about": "About",
  "detail.specialties": "Specialties",
  "detail.languages": "Languages",
  "detail.availability": "Availability this week",
  "detail.hourNote": "All sessions are 1 hour.",
  "detail.reviews": "What clients say",
  "detail.book": "Book this slot",
  "detail.back": "Back to professionals",
  "detail.guestNote": "You’ll choose guest booking or a free account before we hold your slot.",
  "bookChoice.title": "How would you like to book?",
  "bookChoice.body":
    "You can book without an account — or create a free account to keep all your sessions in one place.",
  "bookChoice.guest": "Continue as guest",
  "bookChoice.guestHint": "No account needed · about a minute",
  "bookChoice.account": "Create a free account",
  "bookChoice.accountHint": "Optional — save history and rebook faster",
  "bookChoice.signIn": "Already have an account? Sign in",
  "bookChoice.holding": "Holding your slot…",
  "bookChoice.cancel": "Not now",
  "detail.fee": "$25 / session",
  "detail.video": "Video call",
  "detail.experience": "experience",
  "detail.emptyTitle": "No open slots right now",
  "detail.emptyBody":
    "This counselor hasn't added new times yet. Check back soon or browse similar professionals.",
  "detail.browseSimilar": "Browse similar",
  "onboard.title": "A few quick questions",
  "onboard.sub": "This helps us recommend the right professionals for you.",
  "onboard.looking": "What are you looking for?",
  "onboard.continue": "Continue",
  "onboard.skip": "Skip for now",
  "prefs.title": "What are you looking for?",
  "prefs.sub":
    "Choose the languages you're comfortable with and the kinds of support you want. We'll use these to recommend counselors — you can change them anytime in Account.",
  "prefs.languages": "Preferred language(s)",
  "prefs.carried": "Carried over from step 1 — adjust here if you like.",
  "prefs.pickLang": "Pick every language you're comfortable talking in. At least one is required.",
  "prefs.support": "Types of support",
  "prefs.supportHint": "Check at least one kind of support you're interested in.",
  "prefs.search": "Search types of support…",
  "prefs.growing": "New types of support are added as more counselors join — this list keeps growing.",
  "prefs.back": "Back",
  "prefs.skip": "Skip",
  "prefs.saved": "Your preferences are saved.",
  "clientHome.hello": "Selam, Abel 👋",
  "clientHome.sub": "Here's what's next on your wellness journey.",
  "clientHome.next": "Upcoming session",
  "clientHome.recommended": "Recommended for you",
  "clientHome.continue": "Continue exploring",
  "clientHome.viewAll": "View all",
  "clientHome.bookFirst": "Book your first session",
  "book.title": "Book your session",
  "book.guestTitle": "Book as a guest",
  "book.guestSub": "No account needed. We’ll email your confirmation.",
  "book.firstName": "First name",
  "book.lastName": "Last name (optional)",
  "book.email": "Email",
  "book.phone": "Phone (optional)",
  "book.note": "Note for your counselor (optional)",
  "book.notePlaceholder": "Anything you’d like them to know…",
  "book.privacy": "Your details stay private — always.",
  "book.step1": "1. Your session",
  "book.step2": "2. Choose a 1-hour slot",
  "book.continue": "Continue to payment",
  "book.cancelNote": "Free cancellation up to 24 hours before.",
  "book.duration": "1 hour",
  "pay.title": "Complete your booking",
  "pay.line": "1-hour session with",
  "pay.card": "Card number",
  "pay.expiry": "Expiry",
  "pay.cvc": "CVC",
  "pay.name": "Name on card",
  "pay.demo": "Stripe test checkout — charged at the counselor’s session fee. No account required.",
  "confirm.title": "You're booked!",
  "confirm.sub": "Your session is confirmed.",
  "confirm.view": "View my sessions",
  "confirm.home": "Back home",
  "confirm.browse": "Keep browsing",
  "confirm.joinHint": "Lost this screen? Find your session anytime at Join with code.",
  "confirm.joinLink": "Join with code",
  "join.title": "Find your session",
  "join.sub": "Enter the session code from your confirmation and the email you used to book.",
  "join.code": "Session code",
  "join.codePlaceholder": "AYZ-XXXX",
  "join.email": "Email",
  "join.submit": "Find session",
  "join.notFound": "We couldn’t find a booking with that code and email. Check both and try again.",
  "join.cancelled": "This booking was cancelled. Contact support if you need help.",
  "join.lobbyTitle": "Session lobby",
  "join.lobbySub": "You’re in the right place. Join opens 15 minutes before your session.",
  "join.opensIn": "Join opens in {when}",
  "join.ended": "This session’s join window has ended.",
  "join.ready": "You’re within the join window.",
  "join.videoStub": "Video rooms connect in a later release — your booking is confirmed.",
  "join.another": "Look up another booking",
  "join.addCalendar": "Add to calendar",
  "sessions.title": "My sessions",
  "sessions.upcoming": "Upcoming",
  "sessions.past": "Past",
  "sessions.cancelled": "Cancelled",
  "sessions.emptyTitle": "No sessions yet",
  "sessions.emptyBody": "When you book a session it will appear here.",
  "sessions.join": "Join session",
  "sessions.details": "View details",
  "session.professional": "Professional",
  "session.datetime": "Date & time",
  "session.specialty": "Specialty",
  "session.duration": "Duration",
  "session.language": "Language",
  "session.status": "Status",
  "session.reschedule": "Reschedule",
  "session.cancel": "Cancel booking",
  "session.rescheduleNote": "Rescheduling isn't in v1 — shown disabled",
  "session.cancelConfirm": "Are you sure you want to cancel this session?",
  "session.cancelYes": "Yes, cancel",
  "session.cancelKeep": "Keep session",
  "session.back": "← Back to my sessions",
  "session.format": "Format",
  "session.videoReady": "Your link is ready — it opens 10 minutes before your session.",
  "session.videoPending": "Link available 10 min before",
  "session.fee": "Fee",
  "session.joinNote": "You'll be able to join 15 minutes before your session starts.",
  "proOnboard.title": "Tell us about your practice",
  "proOnboard.sub": "Clients will see this on your public profile.",
  "proOnboard.titleField": "Professional title",
  "proOnboard.city": "City",
  "proOnboard.credentials": "Credentials",
  "proOnboard.bio": "A few sentences about how you work.",
  "proOnboard.stepAbout": "1 · About",
  "proOnboard.stepSpecialties": "2 · Specialties",
  "proOnboard.stepAvailability": "3 · Availability",
  "proOnboard.backRole": "← Back to role selection",
  "proOnboard.langRequired": "Pick at least one language you work in.",
  "proOnboard.specRequired": "Pick at least one specialty.",
  "proOnboard.photo": "Profile photo",
  "proOnboard.changePhoto": "Change photo",
  "proSpecs.cancel": "Cancel",
  "proSpecs.search": "Search specialties…",
  "proSpecs.growing": "New specialties are added as more counselors join — this list keeps growing.",
  "proSpecs.required": "Select at least one specialty to continue.",
  "proProfile.displayName": "Display name",
  "proProfile.titleField": "Professional title",
  "proProfile.city": "City / region",
  "proProfile.bio": "Short bio",
  "proProfile.more": "More about your practice",
  "proProfile.save": "Save changes",
  "proProfile.discard": "Discard",
  "proProfile.saved": "Profile saved.",
  "proProfile.preview": "Public preview",
  "proAvail.closed": "Closed",
  "proAvail.selected": "Selected",
  "proAvail.openLabel": "Available",
  "proAvail.makeAvailable": "Make available",
  "proAvail.removeLabel": "Remove",
  "proAvail.slotsFor": "1-hour slots for",
  "proAvail.save": "Save availability",
  "proAvail.saved": "Availability saved.",
  "proAvail.emptyDay": "No slots for this date yet.",
  "proAvail.emptyTitle": "No slots on this date yet",
  "proAvail.emptyBody": "Tap times below to open them for booking.",
  "proAvail.noChanges": "No changes to save.",
  "proAvail.closeDayConfirm":
    "Saving will close all your slots for this day. Clients won't be able to book it.",
  "proAvail.confirmClose": "Yes, close this day",
  "proAvail.keepEditing": "Keep editing",
  "proAvail.removeTitle": "Remove this time?",
  "proAvail.removeBody": "{time} won’t be bookable after you save.",
  "proAvail.removeConfirm": "Remove availability",
  "proAvail.keepAvailable": "Keep available",
  "proHome.checklistTitle": "Complete your profile",
  "proHome.checklistAbout": "Add your practice details",
  "proHome.checklistSpecs": "Choose specialties",
  "proHome.checklistAvail": "Set availability",
  "proHome.videoDisabled": "Video sessions aren't enabled yet",
  "proPending.title": "Application under review",
  "proPending.body":
    "Thanks for applying. A team member will review your profile before clients can book with you. We'll email you when you're approved.",
  "proPending.home": "Back to welcome",
  "chrome.comingSoon": "Coming soon",
  "proHome.hello": "Good afternoon, Hana 👋",
  "proHome.dateLine": "Saturday, October 3 · Here's your practice today.",
  "proHome.complete": "Complete your profile",
  "proHome.upcoming": "Upcoming bookings",
  "proHome.availability": "Manage availability",
  "proHome.bookings": "View all bookings",
  "proHome.edit": "Edit profile",
  "proHome.sessionsToday": "Sessions today",
  "proHome.avgRating": "Average rating",
  "proHome.earned": "Earned this week",
  "proHome.nextSession": "Next session",
  "proHome.schedule": "Today's schedule",
  "proHome.emptySchedule": "Nothing scheduled today — your open slots are visible to clients",
  "proProfile.title": "Your public profile",
  "proProfile.note": "This is what clients see when they visit your page.",
  "proProfile.edit": "Edit profile",
  "proProfile.specialties": "Manage specialties",
  "proProfile.availability": "Set availability",
  "proSpecs.title": "Your specialties",
  "proSpecs.sub": "Pick the areas you work in. Clients use these to find you.",
  "proSpecs.save": "Save changes",
  "proAvail.title": "Your availability",
  "proAvail.sub": "Pick a date, then tap 1-hour slots to open them for booking.",
  "proAvail.available": "Available",
  "proAvail.booked": "Booked",
  "proAvail.note": "Tap Save availability to keep your changes.",
  "proBookings.title": "Bookings",
  "account.title": "Account settings",
  "account.sub": "Manage how Ayzon looks and works for you.",
  "account.languageHint":
    "Buttons and menus will use this language. A counselor's profile always shows the languages they work in.",
  "account.emailNote":
    "Email can't be changed in v1. If you need a new address, contact support and we'll help.",
  "account.save": "Save changes",
  "account.language": "Preferred language",
  "account.email": "Email",
  "account.changePassword": "Change password",
  "account.signOut": "Sign out",
  "notFound.title": "Page not found",
  "notFound.body": "The page you're looking for doesn't exist or was moved.",
  "notFound.cta": "Go home",
  "error.title": "Something went wrong",
  "error.body": "Please try again in a moment.",
  "error.cta": "Try again",
} as const;

export type CopyKey = keyof typeof en;

export const am: Partial<Record<CopyKey, string>> = {
  "nav.home": "መነሻ",
  "nav.services": "አገልግሎቶች",
  "nav.professionals": "ባለሙያዎች",
  "nav.mySessions": "የእኔ ቀጠሮዎች",
  "nav.sessions": "የእኔ ቀጠሮዎች",
  "nav.signIn": "ይግቡ",
  "nav.createAccount": "መለያ ይፍጠሩ",
  "chrome.mode": "ሁነታ",
  "chrome.bright": "ብሩህ",
  "chrome.night": "ሌሊት",
  "account.signOut": "ይውጡ",
  "home.ctaBrowse": "አማካሪዎችን ይፈልጉ",
  "home.ctaSignIn": "ይግቡ",
  "home.kicker": "አሁን ይመዝገቡ · አካውንት አያስፈልግም",
  "home.guestPromise": "ምዝገባ አያስፈልግም · የይለፍ ቃል አያስፈልግም",
  "home.amharicSub": "የምክር አገልግሎት በራስዎ ቋንቋ",
  "detail.book": "ይያዙ",
  "gate.title": "ይህን ቀጠሮ ለመያዝ ይግቡ",
  "gate.body": "እንደ እንግዳ መፈለግዎን መቀጠል ይችላሉ — ግን ቀጠሮ ለመያዝ ነፃ መለያ ያስፈልጋል። ከገቡ በኋላ ወደዚህ ጊዜ እንመልስዎታለን።",
  "prefs.title": "ምን እየፈለጉ ነው؟",
  "prefs.sub": "የሚመችዎ ቋንቋ እና የሚፈልጉትን የድጋፍ ዓይነት ይምረጡ። እነዚህ ምርጫዎች ተስማሚ አማካሪዎችን እንድንመክር ይረዱናል፤ በማንኛውም ጊዜ መቀየር ይችላሉ።",
  "prefs.languages": "የሚመችዎ ቋንቋ(ዎች)",
  "prefs.support": "የድጋፍ ዓይነቶች",
  "prefs.back": "ተመለስ",
  "prefs.skip": "ዝለል",
  "onboard.continue": "ቀጥል",
  "prefs.saved": "ምርጫዎችዎ ተቀምጠዋል።",
};

export function t(locale: Locale, key: CopyKey): string {
  if (locale === "am" && am[key]) {
    return am[key] as string;
  }
  return en[key];
}
